name: Node.js Package

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.17.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sangamcse'
      - name: Install Dependencies
        run: yarn install
      - run: yarn build && yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
